CREATE TABLE Users (
	UserId INT IDENTITY (1,1) NOT NULL,
	Name VARCHAR(75) NOT NULL,
	Email VARCHAR(75) NOT NULL,
	CPF VARCHAR(75) NOT NULL,
	DataCadastro DATETIMEOFFSET NOT NULL,

	CONSTRAINT PK_Users PRIMARY KEY CLUSTERED (UserId ASC)
);

CREATE TABLE Contacts (
	ContactId INT IDENTITY(1,1) NOT NULL,
	UserId INT NOT NULL,
	Telefone VARCHAR(30) NOT NULL,
	Celular VARCHAR(30) NOT NULL,

	CONSTRAINT PK_Contacts PRIMARY KEY CLUSTERED (ContactId ASC),
	CONSTRAINT FK_Contacts_Users FOREIGN KEY (UserId) REFERENCES Users (UserId) ON DELETE CASCADE
);

CREATE TABLE Account (
	AccountId INT IDENTITY(1,1) NOT NULL,
	UserId INT NOT NULL,
	AccountNumber VARCHAR(30) NOT NULL,
	Password VARCHAR(30) NOT NULL,
	Balance DECIMAL(18,2) NOT NULL,
	AccounType VARCHAR(20) NOT NULL,
	DataCadastro DATETIMEOFFSET NOT NULL,

	CONSTRAINT PK_Account PRIMARY KEY CLUSTERED (AccountId ASC),
	CONSTRAINT FK_Account_Users FOREIGN KEY (UserId) REFERENCES Users (UserId) ON DELETE CASCADE
);